[package]
name = "example"
version = "0.0.10"
edition = "2024"

[dependencies]
afast = { path = "../afast" }
tokio = { version = "1", features = ["full"] }

[features]
default = ["tcp", "http", "ws", "doc", "js", "ts", "trace"]
js = ["afast/js"]
ts = ["afast/ts"]
tcp = ["afast/tcp"]
http = ["afast/http"]
ws = ["afast/ws"]
doc = ["afast/doc"]
trace = ["afast/trace"]
