[package]
name = "example"
version = "0.0.7"
edition = "2024"

[dependencies]
afast = { path = "../afast" }
tokio = { version = "1", features = ["full"] }

[features]
default = ["http", "doc", "js", "ts"]
js = ["afast/js"]
ts = ["afast/ts"]
tcp = ["afast/tcp"]
http = ["afast/http"]
ws = ["afast/ws"]
doc = ["afast/doc"]
