# Http test


### GET
GET http://127.0.0.1:3000/hello/world5?sorts=-id,name&size=2&page=1
Content-Type: application/json


### GET BY ID
GET http://127.0.0.1:3000/hello/world5/1
Content-Type: application/json


### POST
POST http://127.0.0.1:3000/hello/world5
Content-Type: application/json

{
    "name": "ahriknow",
    "age": 18,
    "username": "username",
    "password": "password"
}


### PUT
PUT http://127.0.0.1:3000/hello/world5/1
Content-Type: application/json

{
    "name": "ahriknow"
}


### DELETE
DELETE http://127.0.0.1:3000/hello/world5/1
Content-Type: application/json
